### ISSUE TITLE
Installing FFMPEG

### ISSUE THREAD

**Issue by Articomb** [SuperZombi/GICutscenesUI#10]
Everything seems to be working fine, Ive successfully extracted the files using your program but idk how to install ffmpeg properly for it to be merged.

Sorry Im not very technical at using programs like these, Im not a coder.

**Comment by Articomb** [comment]
figured it out by placing the ffmpeg exe in the folder where the GICutsceneUI.exe file was placed

**Comment by SuperZombi** [comment]
> figured it out by placing the ffmpeg exe in the folder where the GICutsceneUI.exe file was placed

Yes. Alternatively, you can add it to PATH
