### ISSUE TITLE
关于合并视频后字幕有黑边，支持修改吗

### ISSUE THREAD

**Issue by duanxiaosheng** [SuperZombi/GICutscenesUI#15]
![image](https://user-images.githubusercontent.com/48898646/209475421-2f670085-c5cc-4c92-b233-529f89106ec7.png)

**Comment by SuperZombi** [comment]
https://github.com/ToaHartor/GI-cutscenes

**Comment by duanxiaosheng** [comment]
@SuperZombi 
版本:0.4.0.1  中有字幕选项
![image](https://user-images.githubusercontent.com/48898646/209535738-9ae070cf-1b41-4442-a30e-4f048cc45221.png)

---------------------------------------------------

版本:0.4.3.1  没有了字幕选项，这是什么原因
![image](https://user-images.githubusercontent.com/48898646/209535431-4465c38a-0781-411a-a8cd-84386ba0a7ba.png)

**Comment by SuperZombi** [comment]
Subtitles have not been implemented.
