### ISSUE TITLE
Failed to launch the app using Chrome browser...

### ISSUE THREAD

**Issue by immediately233** [SuperZombi/GICutscenesUI#16]
![图片](https://user-images.githubusercontent.com/68837366/213351256-696f7c7e-e9e3-4106-ab58-90cdefc1bc53.png)

**Comment by SuperZombi** [comment]
If you don't have Chrome installed, the app will try to run in other browsers. Considering by your logs, it should have opened in Edge.

**Comment by immediately233** [comment]
I have my Edge removed.

**Comment by GID0317** [comment]
You should not uninstall it, Because as i heard it can broke the system and cause the problem if you force uninstall it

**Comment by immediately233** [comment]
Edge can be uninstalled gracefully without breaking system

**Comment by GID0317** [comment]
Okay thats good to hear, anyways so you have solved the problem? Im not a m$ fans or something like that, but its not hurt to try reinstall the edge to double check if this workaround work

**Comment by SuperZombi** [comment]
@immediately233, If you want to get help. Please describe in detail what system are you using, how you run the application, and what you get.
As I said earlier, the program uses the browser engine to display the interface. And in order for it to run, you need a browser. What browser do you have by default?

```python
for browser in ['chrome', 'edge', 'default']:
	try:
		eel.start()
	except:
		print(f"Failed to launch the app using {browser.title()}")
```

**Comment by Jerry12228** [comment]
我遇到了同样的问题，我的系统中有chrome edge，事实上他们都启动并打开了一个页面
![image](https://github.com/SuperZombi/GICutscenesUI/assets/86408775/14948df7-b31b-4f64-9cd5-57c85f6c9f11)
但主程序闪退了，输出了同样的 日志
![](https://user-images.githubusercontent.com/68837366/213351256-696f7c7e-e9e3-4106-ab58-90cdefc1bc53.png)
