### ISSUE TITLE
Add Japanese Translation

### ISSUE THREAD

**Issue by cotore-game** [SuperZombi/GICutscenesUI#19]
I hope I can select Japanese, but can I change the Json file or HTML?
I'm beginner of GitHub, so I don't really understand the rules and Github's system.
[jp.json](https://github.com/SuperZombi/GICutscenesUI/files/13760899/jp.json)

**Comment by GID0317** [comment]
I think that’s okay! All you have left to do is edit the main.html and you should be done. Maybe I can help you if you want

**Comment by GID0317** [comment]
Okay done, you can check it here maybe there was an error or something like that. So this can be merged soon by the SuperZombi

https://github.com/GID0317/GICutscenesUI/blob/main/GICutscenesUI/web/main.html

https://github.com/GID0317/GICutscenesUI/blob/main/GICutscenesUI/web/locales/jp.json

**Comment by cotore-game** [comment]
Thank you so much!
I really appreciate your kindness

**Comment by GID0317** [comment]
No problem! Glad to help. I create a pull request and just wait to be merged

https://github.com/SuperZombi/GICutscenesUI/pull/20

**Comment by SuperZombi** [comment]
`raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

**Comment by SuperZombi** [comment]
Fixed by replacing `utf-8` on `utf-8-sig`:
```python
with open(tr_file, 'r', encoding="utf-8-sig") as file:
	string = file.read()
```
