### ISSUE TITLE
localhost not sending any data

### ISSUE THREAD

**Issue by minecraft4668** [SuperZombi/GICutscenesUI#21]
当我尝试打开GICutsencesUI.exe时，它们弹出了几个网页。但是都显示localhost 未发送任何数据。这是怎么回事？

**Comment by SuperZombi** [comment]
Please use english. Describe the characteristics of your system

**Comment by minecraft4668** [comment]
When I tried to open the GICutsencesUI.exe, they popped up several web pages. But both show localhost not sending any data. What's going on?

**Comment by minecraft4668** [comment]
I'm so sorry about that I didn't use English.

**Comment by SuperZombi** [comment]
show screenshot

**Comment by minecraft4668** [comment]
![image](https://github.com/SuperZombi/GICutscenesUI/assets/132268400/b694ef1d-d067-48c9-9274-cb4895f3cf33)
This is what it shows when I try to start it.

**Comment by SuperZombi** [comment]
idk. i'm using chrome and it is okay in it

**Comment by minecraft4668** [comment]
I also tried chrome.But it still not work.

**Comment by SuperZombi** [comment]
version of your OS and version of GICutsencesUI u downloaded pls

**Comment by minecraft4668** [comment]
i tried it when im playing genshin and it suddenly opened, it was so amazing!
![image](https://github.com/SuperZombi/GICutscenesUI/assets/132268400/c5399f00-0702-4fe7-bdd9-bbb334c9efdb)

**Comment by minecraft4668** [comment]
i try to stop a music software called kugou.and it works!sorry for wasting your time.
