### ISSUE TITLE
App opens Microsoft Edge instead of the default browser

### ISSUE THREAD

**Issue by Caelum008** [SuperZombi/GICutscenesUI#22]
Is there anyway I can redirect the app to open Opera GX instead? It used to do that before updating to 0.5.0.

Thanks.

**Comment by SuperZombi** [comment]
1) It doesn't matter in which browser engine app runs. 
2) I don't change startup browsers logic in 5.0. It's same with 4.0. 
3) App trying to launch Chrome. If you don't have it, it try launch Edge and finally launch the default browser in new tab.
