### ISSUE TITLE
When using merge video and audio,the file,mp4 bitrate is lower than the orginal m2v?

### ISSUE THREAD

**Issue by Liujunhua007** [SuperZombi/GICutscenesUI#24]
can see the mp4 scenes are more blur.
![image](https://github.com/SuperZombi/GICutscenesUI/assets/62129047/ebbad94a-f294-4f21-83d2-9b5d42e2b1ee)
this option.
is there a way to fix it? maybe the ffmpeg properties setted wrong

**Comment by SuperZombi** [comment]
I don't know how to get a high bitrate. now I use the flag `-b:v 10M`

**Comment by Liujunhua007** [comment]
> I don't know how to get a high bitrate. now I use the flag `-b:v 10M`

i dont know as well，suggust that merge by mkvtool directly，because i done this manually the mkv is high rate 20-30k

**Comment by SuperZombi** [comment]
Can you tell me in which video you saw a bad bitrate?
The source has a bitrate of 9000 in VP9. I encode 10000 MPEG. I look now and see that the video quality is acceptable. I can increase the bitrate if you want. Or try converting manually

**Comment by SuperZombi** [comment]
I added bitrate selection in b4d6e5d
<img src="https://github.com/SuperZombi/GICutscenesUI/assets/75096786/b3529394-6be2-41ea-a96c-ce2df8af74dc" width="500">
