### ISSUE TITLE
11 specific cutscenes do not have their second key in versions.json

### ISSUE THREAD

**Issue by Boyishdude** [SuperZombi/GICutscenesUI#27]
I was able to extract and convert all 134 other cutscenes just fine with your GUI tool, but these 11 cutscenes could not be extracted and converted:

![The eleven cutscenes I could not extract and convert.](https://github.com/user-attachments/assets/af99fc07-cfac-4373-9ac2-f265815fc842)

And all 11 of them gave me the same error message: 

![The second key doesn't exist for some reason.](https://github.com/user-attachments/assets/94a2813d-797f-41e7-b848-fd30bd5eb277)

Given all the possibilities, in my mind, this is obviously an error with the program itself, given that I didn't have any problems with the other 134 cutscenes. It would be weird if the reason was that I had not properly installed the original version of the tool (though I did download and extract its Standalone version), given that these are the only cutscenes I had a problem with. It even extracted and converted them without also applying the subtitles, which is exactly what I wanted. I didn't want to have to use some clunky AI watermark remover that leaves obvious traces of itself to get rid of the text.

**Comment by SuperZombi** [comment]
### You need to update versions.json on About tab
![image](https://github.com/user-attachments/assets/47b597f7-94ec-485c-850a-3065ae52a925)
