### ISSUE TITLE
Since version 4.31, there has been no executable program. How should I use it?

### ISSUE THREAD

**Issue by stargod-1** [SuperZombi/GICutscenesUI#28]
I downloaded three compressed files, but I didn't see any executable files. I only see one HTML file available. After I clicked on it, there were only UI illegal settings and adding USM files. Can anyone tell me how to use it?

**Comment by stargod-1** [comment]
If there are tutorials to recommend, thanks

**Comment by stargod-1** [comment]
Thanks for your reply. All I want is to use the new version of the UI, which is version 6.0. But version 6.0 doesn't have an executable like 4.3.1 (.exe)

**Comment by stargod-1** [comment]
Thanks for your reply. All I want is to use the new version of the UI, which is version 6.0. But version 6.0 doesn't have an executable like 4.3.1 (.exe)

**Comment by stargod-1** [comment]
Or should I use the html file in the 6.0 archive?

**Comment by stargod-1** [comment]
Or do you have time to record a video and send it to me, thanks

**Comment by SuperZombi** [comment]
Just download this and unzip it. 
![IMG_20240829_210911](https://github.com/user-attachments/assets/771c6b1a-7d34-4549-bdc3-568c7eb665ba)
