### ISSUE TITLE
Unable to find second key?

### ISSUE THREAD

**Issue by Toa-Pohatu** [SuperZombi/GICutscenesUI#29]
I have my genshin impact on my D drive, do I need to do anything with the settings to make it find the right file or does it do that when I select the file I want to convert from the main app page? I get this error about a second key, so I'm not sure.

Finding encryption key for Cs_Natlan_AQ50120901_MVBT.usm...
System.Collections.Generic.KeyNotFoundException: Unable to find the second key in versions.json for Cs_Natlan_AQ50120901_MVBT

**Comment by SuperZombi** [comment]
Try to open the app settings > update `vesions.json`
If it doesn't help, ask https://github.com/ToaHartor/GI-cutscenes

**Comment by SuperZombi** [comment]
I think your problem is related to the fact that there are no keys for version 5.1 yet. Wait a bit. If your problem will not be solved, reopen this ticket.
