### ISSUE TITLE
Update Chinese translation

### ISSUE THREAD

**Issue by SuperZombi** [SuperZombi/GICutscenesUI#3]
@zhxycn, pls update your translation, because [en.json](https://github.com/SuperZombi/GICutscenesUI/blob/main/GICutscenesUI/web/locales/en.json) was updated.

**Comment by zhxycn** [comment]
Okay, tonight.

**Comment by zhxycn** [comment]
#4 Already updated the translation.

**Comment by SuperZombi** [comment]
@zhxycn, i also changed "export" and "export_title" values to "save" and "save_title". change it too pls

**Comment by zhxycn** [comment]
#5 Changed. Anything else?

**Comment by SuperZombi** [comment]
Thanks. I thought that the phrases should be changed there too, but that's all

**Comment by zhxycn** [comment]
No. The phrases don't need changing. They express the right meanings.

**Comment by EIGHTfs** [comment]
非常好用，感谢

**Comment by SuperZombi** [comment]
@zhxycn, I think that Chinese and Chinese traditional are somewhat similar. Is it possible to make one of them inherit from the English language, and the other from the family.
For ex:
ENGLISH --> zh-hans --> zh-hant

For comparison, now both languages are inherited from English.
ENGLISH --> zh-hans 
ENGLISH --> zh-hant

**Comment by zhxycn** [comment]
That's good. Simplified Chinese is more widely used than Traditional Chinese. So try this
`en → zh-hans`
`zh-hans → zh-hant`
